-- 노트 시드는 더 이상 여기서 하지 않는다(supabase-auth-rls).
-- RLS가 user_id = auth.uid()로 잠겨, 노트는 데모 유저 소유로 만들어야 보인다.
-- `supabase start`는 auth 유저가 아직 없을 때 seed.sql을 적용하므로, 데모 계정 생성 +
-- 그 소유 노트 시드는 `e2e/seed.mjs`(서버 기동 후 service_role admin.createUser)가 담당한다.
